services:
  miroworld:
    image: ghcr.io/qi-1021/miroworld:latest
    # 加速镜像（如拉取缓慢可替换上方地址）
    # image: ghcr.nju.edu.cn/qi-1021/miroworld:latest
    container_name: miroworld
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads